### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by Coehill** [ennur/FirestoreRecyclerAdapterSample#1]
Would it be possible to include a screenshot of the Cloud Firestore Dashboard for the database used in the example?  This could help me to read the code better and understand how I could replicate it.

**Comment by nrohmen** [comment]
Hi, Sure.

![Screenshot Firestore Dashboard](https://i.imgur.com/olEDnhv.png)

**Comment by Coehill** [comment]
Great, thanks!  I updated the readme.
